DROP TABLE IF EXISTS WAREHOUSE;
DROP TABLE IF EXISTS WAREHOUSE_PRODUCT;
DROP TABLE IF EXISTS WAREHOUSE_TYPE;

CREATE TABLE WAREHOUSE
(
    ID                INT AUTO_INCREMENT PRIMARY KEY,
    NAME              VARCHAR(100) NOT NULL,
    WAREHOUSE_NUMBER  VARCHAR(10)  NOT NULL,
    CAPACITY          INT(10)      NOT NULL,
    WAREHOUSE_TYPE_ID INT          NOT NULL
);

CREATE TABLE WAREHOUSE_PRODUCT
(
    ID           INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_ID   INT     NOT NULL,
    WAREHOUSE_ID INT     NOT NULL,
    COUNT        INT(10) NOT NULL
);

CREATE TABLE WAREHOUSE_TYPE
(
    ID   INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    CODE VARCHAR(100) NOT NULL
);


ALTER TABLE WAREHOUSE
    ADD FOREIGN KEY (WAREHOUSE_TYPE_ID) REFERENCES WAREHOUSE_TYPE (ID);

ALTER TABLE WAREHOUSE_PRODUCT
    ADD FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSE (ID);