server:
  port: 8081

logging:
  level:
    org.spring.framework.web: debug

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/.well-known/jwks.json

