INSERT INTO PRODUCT_CATEGORY (NAME, CODE) VALUES ( 'car','CR');
INSERT INTO PRODUCT_CATEGORY (NAME, CODE) VALUES ( 'gun','GN');

INSERT INTO PRODUCT (NAME, PRICE, MANUFACTURE_DATE, PRODUCT_CATEGORY_ID) VALUES ( 'bmw ix3',1250000,TO_DATE( '12-FEB-2020', 'DD-MON-YYYY' ),1);
INSERT INTO PRODUCT (NAME, PRICE, MANUFACTURE_DATE, PRODUCT_CATEGORY_ID) VALUES ( '2mm Kolibri',6000,TO_DATE( '14-NOV-2001', 'DD-MON-YYYY' ),2);

INSERT INTO PRODUCT_DETAIL (WEIGHT, WIDTH, HEIGHT, COLOR) VALUES ( 12,2,2,'GREEN' );
INSERT INTO PRODUCT_DETAIL (WEIGHT, WIDTH, HEIGHT, COLOR) VALUES ( 12,1,1,'BLACK' );

INSERT INTO PRODUCT_COMMENT (USER_ID, PRODUCT_ID, MESSAGE) VALUES ( 1,1,'very good car' );
INSERT INTO PRODUCT_COMMENT (USER_ID, PRODUCT_ID, MESSAGE) VALUES ( 1,2,'very bad gun' );
INSERT INTO PRODUCT_COMMENT (USER_ID, PRODUCT_ID, MESSAGE) VALUES ( 2,1,'very bad car' );





