DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS PRODUCT_DETAIL;
DROP TABLE IF EXISTS PRODUCT_CATEGORY;
DROP TABLE IF EXISTS PRODUCT_COMMENT;

CREATE TABLE PRODUCT
(
    ID                  INT AUTO_INCREMENT PRIMARY KEY,
    NAME                VARCHAR(500) NOT NULL,
    PRICE               NUMBER(10)   NOT NULl,
    MANUFACTURE_DATE    DATE         NOT NULL,
    PRODUCT_CATEGORY_ID INT          NOT NULL
);

CREATE TABLE PRODUCT_DETAIL
(
    ID     INT AUTO_INCREMENT PRIMARY KEY,
    WEIGHT INT,
    WIDTH  INT,
    HEIGHT INT,
    COLOR  VARCHAR(20)
);

CREATE TABLE PRODUCT_CATEGORY
(
    ID   INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR NOT NULL,
    CODE VARCHAR NOT NULL
);

CREATE TABLE PRODUCT_COMMENT
(
    ID         INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID    INT          NOT NULL,
    PRODUCT_ID INT          NOT NULL,
    MESSAGE    VARCHAR(500) NOT NULL
);

ALTER TABLE PRODUCT
    ADD FOREIGN KEY (PRODUCT_CATEGORY_ID) REFERENCES PRODUCT_CATEGORY (ID);
ALTER TABLE PRODUCT_DETAIL
    ADD FOREIGN KEY (ID) REFERENCES PRODUCT (ID);
ALTER TABLE PRODUCT_COMMENT
    ADD FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID);