INSERT INTO PAYMENT_TYPE (NAME, CODE)
VALUES ('cash', 'CS'),
       ('check', 'cc'),
       ('creditCard', 'cr');

INSERT INTO ACCOUNT (USER_ID, CREATION_DATE, LOCKED)
VALUES (1, TO_DATE('2-NOV-2019', 'DD-MON-YYYY'), 0);

INSERT INTO BILL (ACCOUNT_ID, PURCHASE_ID, TOTAL_AMOUNT, TOTAL_COUNT, PAYMENT_TYPE_ID)
VALUES (1, 1, 10000, 2, 1);